version: '3'

services:
  app:
    build: .
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    container_name: nestjs_doctor
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    build: ./.docker/mysql
    container_name: mysql_doctor
    restart: always
    tty: true
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=doctor
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
